\hypertarget{classunix__error}{}\doxysection{unix\+\_\+error类 参考}
\label{classunix__error}\index{unix\_error@{unix\_error}}


a \mbox{\hyperlink{classtagged__error}{tagged\+\_\+error}} for syscalls  




{\ttfamily \#include $<$util.\+hh$>$}



类 unix\+\_\+error 继承关系图\+:
% FIG 0


unix\+\_\+error 的协作图\+:
% FIG 1
\doxysubsection*{Public 成员函数}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classunix__error_aa481b9c8bb3c13ce1cb6aa1bf3f667e2}{unix\+\_\+error}} (const std\+::string \&attempt, const int error=errno)
\end{DoxyCompactItemize}


\doxysubsection{详细描述}
a \mbox{\hyperlink{classtagged__error}{tagged\+\_\+error}} for syscalls 

在文件 util.\+hh 第 33 行定义.



\doxysubsection{构造及析构函数说明}
\mbox{\Hypertarget{classunix__error_aa481b9c8bb3c13ce1cb6aa1bf3f667e2}\label{classunix__error_aa481b9c8bb3c13ce1cb6aa1bf3f667e2}} 
\index{unix\_error@{unix\_error}!unix\_error@{unix\_error}}
\index{unix\_error@{unix\_error}!unix\_error@{unix\_error}}
\doxysubsubsection{\texorpdfstring{unix\_error()}{unix\_error()}}
{\footnotesize\ttfamily unix\+\_\+error\+::unix\+\_\+error (\begin{DoxyParamCaption}\item[{const std\+::string \&}]{attempt,  }\item[{const int}]{error = {\ttfamily errno} }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}, {\ttfamily [explicit]}}

brief Construct from a syscall name and the resulting errno 
\begin{DoxyParams}[1]{参数}
\mbox{\texttt{ in}}  & {\em attempt} & is the name of the syscall attempted \\
\hline
\mbox{\texttt{ in}}  & {\em error} & is the errno(3) that resulted \\
\hline
\end{DoxyParams}


在文件 util.\+hh 第 38 行定义.



该类的文档由以下文件生成\+:\begin{DoxyCompactItemize}
\item 
libsponge/util/util.\+hh\end{DoxyCompactItemize}
